// import type { ColorSystemOptions } from '@mui/material/styles';

// import { california, kepple, neonBlue, nevada, redOrange, shakespeare, stormGrey } from './colors';
// import type { ColorScheme } from './types';

// export const colorSchemes = {
//   dark: {
//     palette: {
//       action: { disabledBackground: 'rgba(0, 0, 0, 0.12)' },
//       background: {
//         default: 'var(--mui-palette-neutral-950)',
//         defaultChannel: '9 10 11',
//         paper: 'var(--mui-palette-neutral-900)',
//         paperChannel: '19 78 72',
//         level1: 'var(--mui-palette-neutral-800)',
//         level2: 'var(--mui-palette-neutral-700)',
//         level3: 'var(--mui-palette-neutral-600)',
//       },
//       common: { black: '#000000', white: '#ffffff' },
//       divider: 'var(--mui-palette-neutral-700)',
//       dividerChannel: '50 56 62',
//       error: {
//         ...redOrange,
//         light: redOrange[300],
//         main: redOrange[400],
//         dark: redOrange[500],
//         contrastText: 'var(--mui-palette-common-black)',
//       },
//       info: {
//         ...shakespeare,
//         light: shakespeare[300],
//         main: shakespeare[400],
//         dark: shakespeare[500],
//         contrastText: 'var(--mui-palette-common-black)',
//       },
//       neutral: { ...nevada },
//       primary: {
//         ...neonBlue,
//         light: neonBlue[300],
//         main: neonBlue[400],
//         dark: neonBlue[500],
//         contrastText: 'var(--mui-palette-common-black)',
//       },
//       secondary: {
//         ...nevada,
//         light: nevada[100],
//         main: nevada[200],
//         dark: nevada[300],
//         contrastText: 'var(--mui-palette-common-black)',
//       },
//       success: {
//         ...kepple,
//         light: kepple[300],
//         main: kepple[400],
//         dark: kepple[500],
//         contrastText: 'var(--mui-palette-common-black)',
//       },
//       text: {
//         primary: 'var(--mui-palette-neutral-100)',
//         primaryChannel: '240 244 248',
//         secondary: 'var(--mui-palette-neutral-400)',
//         secondaryChannel: '159 166 173',
//         disabled: 'var(--mui-palette-neutral-600)',
//       },
//       warning: {
//         ...california,
//         light: california[300],
//         main: california[400],
//         dark: california[500],
//         contrastText: 'var(--mui-palette-common-black)',
//       },
//     },
//   },
//   light: {
//     palette: {
//       action: { disabledBackground: 'rgba(0, 0, 0, 0.06)' },
//       background: {
//         default: 'var(--mui-palette-common-white)',
//         defaultChannel: '255 255 255',
//         paper: 'var(--mui-palette-common-white)',
//         paperChannel: '255 255 255',
//         level1: 'var(--mui-palette-neutral-50)',
//         level2: 'var(--mui-palette-neutral-100)',
//         level3: 'var(--mui-palette-neutral-200)',
//       },
//       common: { black: '#000000', white: '#ffffff' },
//       divider: 'var(--mui-palette-neutral-200)',
//       dividerChannel: '220 223 228',
//       error: {
//         ...redOrange,
//         light: redOrange[400],
//         main: redOrange[500],
//         dark: redOrange[600],
//         contrastText: 'var(--mui-palette-common-white)',
//       },
//       info: {
//         ...shakespeare,
//         light: shakespeare[400],
//         main: shakespeare[500],
//         dark: shakespeare[600],
//         contrastText: 'var(--mui-palette-common-white)',
//       },
//       neutral: { ...stormGrey },
//       primary: {
//         ...neonBlue,
//         light: neonBlue[400],
//         main: neonBlue[500],
//         dark: neonBlue[600],
//         contrastText: 'var(--mui-palette-common-white)',
//       },
//       secondary: {
//         ...nevada,
//         light: nevada[600],
//         main: nevada[700],
//         dark: nevada[800],
//         contrastText: 'var(--mui-palette-common-white)',
//       },
//       success: {
//         ...kepple,
//         light: kepple[400],
//         main: kepple[500],
//         dark: kepple[600],
//         contrastText: 'var(--mui-palette-common-white)',
//       },
//       text: {
//         primary: 'var(--mui-palette-neutral-900)',
//         primaryChannel: '33 38 54',
//         secondary: 'var(--mui-palette-neutral-500)',
//         secondaryChannel: '102 112 133',
//         disabled: 'var(--mui-palette-neutral-400)',
//       },
//       warning: {
//         ...california,
//         light: california[400],
//         main: california[500],
//         dark: california[600],
//         contrastText: 'var(--mui-palette-common-white)',
//       },
//     },
//   },
// } satisfies Partial<Record<ColorScheme, ColorSystemOptions>>;
import type { ColorSystemOptions } from '@mui/material/styles';
import { red } from '@mui/material/colors';
import type { ColorScheme } from './types';

const customYellow = {
  100: '#FFF9C4',
  200: '#FFF59D',
  300: '#FFF176',
  400: '#FFEE58',
  500: '#FEE135', // Your desired yellow color
  600: '#FDD835',
  700: '#FBC02D',
  800: '#F9A825',
  900: '#F57F17',
  A100: '#FFFF8D',
  A200: '#FFFF00',
  A400: '#FFEA00',
  A700: '#FFD600',
};

export const colorSchemes = {
  dark: {
    palette: {
      action: { disabledBackground: 'rgba(0, 0, 0, 0.12)' },
      background: {
        default: '#121212',
        defaultChannel: '18 18 18',
        paper: '#1E1E1E',
        paperChannel: '30 30 30',
        level1: '#282828',
        level2: '#323232',
        level3: '#3C3C3C',
      },
      common: { black: '#000000', white: '#ffffff' },
      divider: '#424242',
      dividerChannel: '66 66 66',
      error: {
        ...red,
        light: red[300],
        main: red[400],
        dark: red[500],
        contrastText: '#ffffff',
      },
      info: {
        ...customYellow,
        light: customYellow[300],
        main: customYellow[400],
        dark: customYellow[500],
        contrastText: '#000000',
      },
      neutral: {
        100: '#ffffff',
        200: '#F0F0F0',
        300: '#E0E0E0',
        400: '#BDBDBD',
        500: '#9E9E9E',
        600: '#757575',
        700: '#616161',
        800: '#424242',
        900: '#212121',
        950: '#121212',
      },
      primary: {
        ...red,
        light: red[300],
        main: red[400],
        dark: red[500],
        contrastText: '#ffffff',
      },
      secondary: {
        ...customYellow,
        light: customYellow[300],
        main: customYellow[400],
        dark: customYellow[500],
        contrastText: '#000000',
      },
      success: {
        ...customYellow,
        light: customYellow[300],
        main: customYellow[400],
        dark: customYellow[500],
        contrastText: '#000000',
      },
      text: {
        primary: '#ffffff',
        primaryChannel: '255 255 255',
        secondary: '#BDBDBD',
        secondaryChannel: '189 183 183',
        disabled: '#757575',
      },
      warning: {
        ...customYellow,
        light: customYellow[300],
        main: customYellow[400],
        dark: customYellow[500],
        contrastText: '#000000',
      },
    },
  },
  light: {
    palette: {
      action: { disabledBackground: 'rgba(0, 0, 0, 0.06)' },
      background: {
        default: '#ffffff',
        defaultChannel: '255 255 255',
        paper: '#ffffff',
        paperChannel: '255 255 255',
        level1: '#F8F8F8',
        level2: '#F0F0F0',
        level3: '#E8E8E8',
      },
      common: { black: '#000000', white: '#ffffff' },
      divider: '#E0E0E0',
      dividerChannel: '224 224 224',
      error: {
        ...red,
        light: red[400],
        main: red[500],
        dark: red[600],
        contrastText: '#ffffff',
      },
      info: {
        ...customYellow,
        light: customYellow[400],
        main: customYellow[500],
        dark: customYellow[600],
        contrastText: '#000000',
      },
      neutral: {
        100: '#F5F5F5',
        200: '#EEEEEE',
        300: '#E0E0E0',
        400: '#BDBDBD',
        500: '#9E9E9E',
        600: '#757575',
        700: '#616161',
        800: '#424242',
        900: '#212121',
        950: '#121212',
      },
      primary: {
        ...red,
        light: red[400],
        main: red[500],
        dark: red[600],
        contrastText: '#ffffff',
      },
      secondary: {
        ...customYellow,
        light: customYellow[400],
        main: customYellow[500],
        dark: customYellow[600],
        contrastText: '#000000',
      },
      success: {
        ...customYellow,
        light: customYellow[400],
        main: customYellow[500],
        dark: customYellow[600],
        contrastText: '#000000',
      },
      text: {
        primary: '#212121',
        primaryChannel: '33 33 33',
        secondary: '#757575',
        secondaryChannel: '117 117 117',
        disabled: '#BDBDBD',
      },
      warning: {
        ...customYellow,
        light: customYellow[400],
        main: customYellow[500],
        dark: customYellow[600],
        contrastText: '#000000',
      },
    },
  },
} satisfies Partial<Record<ColorScheme, ColorSystemOptions>>;